### ISSUE TITLE
Internal Server Error with new install of Next.js v13 and next-on-pages v0.5

### ISSUE THREAD

**Issue by danielrhodes** [cloudflare/next-on-pages#126]
I just did a fresh install of next.js v13 with typescript. Followed directions in the README here. Hardly any changes to the base install. The deploy goes through without an issue. However, when I attempt to load the site, I get `Internal Server Error` with no other information. What can do I do here?

> package.json
```json
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "13.2.4",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.9",
    "autoprefixer": "^10.4.14",
    "postcss": "^8.4.21",
    "@cloudflare/next-on-pages": "^0.5.0",
    "@types/node": "18.15.5",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "eslint": "8.36.0",
    "eslint-config-next": "13.2.4",
    "typescript": "5.0.2",
    "tailwindcss": "^3.2.7"
  }
}
```

> next.config.js
```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    appDir: true,
    runtime: "experimental-edge",
  },
};

module.exports = nextConfig;
```

Response:

```
HTTP/1.1 500 Internal Server Error
CF-RAY: 7abbb5c568b9cf4d-SJC
Connection: keep-alive
Content-Length: 21
Content-Type: text/html; charset=utf-8
Date: Wed, 22 Mar 2023 04:32:18 GMT
ETag: "66fci67lppl"
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=AkSmM2fQ3drv5KbY76SmixV1MHwjwxnSbMxoCrrVZQmUT4H%2B9MA6c3ccX8OOtW36h35rpUBuxd23CyTWY2Vjg1Y%2FI%2B6mOshCrXyo95cKFm%2F8KYqVt3EChK8G4scg18GRo4SmTZvxlffHC8s9AH3K66gSYihveycD4EM%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Accept-Encoding
X-Edge-Runtime: 1
X-Powered-By: Next.js
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400

Internal Server Error
```

**Comment by dario-piotrowicz** [comment]
does the app work locally? (if you build it via next-on-pages and run it using wrangler)

also did you remember to set the `NODE_VERSION` and `nodejs_compat` in the dashboard?

**Comment by danielrhodes** [comment]
It does work locally if I am using the `next dev` and it works if I deploy it to Vercel. I had not tried running it locally using Wrangler. That appears to have exposed the issue:

```javascript
GET / 500 Internal Server Error (535.91ms, waitUntil: 535.93ms)
Error: Invariant: AsyncLocalStorage accessed in runtime where it is not available
    at n.run (/private/<redacted>/.vercel/output/static/_worker.js:1216:17)
    at Function.wrap (/private/<redacted>/.vercel/output/static/_worker.js:9391:21)
    at e3 (/private/<redacted>/.vercel/output/static/_worker.js:9363:21)
    at ts.renderHTML (/private<redacted>/.vercel/output/static/_worker.js:8381:26)
    at U2 (/private/<redacted>/.vercel/output/static/_worker.js:7840:490)
    at q2.responseCache.get.incrementalCache (/private/<redacted>/.vercel/output/static/_worker.js:7864:28)
    at /private/<redacted>/.vercel/output/static/_worker.js:8071:30
    at e5.get (/private/<redacted>/.vercel/output/static/_worker.js:8078:11)
    at ts.renderToResponseWithComponentsImpl (/private/<redacted>/.vercel/output/static/_worker.js:7860:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of null (reading 'default')
    at Object.loadComponent (/private/<redacted>/.vercel/output/static/_worker.js:8471:1167)
    at ts.findPageComponents (/private/<redacted>/.vercel/output/static/_worker.js:8402:61)
    at ts.renderErrorToResponseImpl (/private/<redacted>/.vercel/output/static/_worker.js:7997:263)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ts.renderToResponseImpl (/private/<redacted>/.vercel/output/static/_worker.js:7962:22)
```

A separate request: it would be helpful if I could see this error on Cloudflare's dashboard. I looked around for something like this, and couldn't find it, which hindered my ability to find the actual error. If there's a place/person I can reach out to to deliver that feedback, I would be happy to do so and explain why it is a priority.

**Comment by danielrhodes** [comment]
Ok update: I was able to get it running locally, although I'm not sure what I changed. I added the `nodejs_compat` flag to my wrangler call and restarted the watcher. It did not immediately work but eventually did. I already had this flag set in production.

> `npx wrangler pages dev .vercel/output/static  --compatibility-flag=nodejs_compat`

However, now when I deploy I still get an error when I go to a specific route.

> Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

What might be important here is that this route is dynamic, and it is using the `fetch` command in NextJS 13. This route works locally. I can't see any logs that would help provide more useful info.

**Comment by wuomzfx** [comment]
Same error

**Comment by wuomzfx** [comment]
Maybe it's this problem. https://github.com/vercel/next.js/issues/46337

I fixed it using next@canary.

**Comment by ThuKieuIC2** [comment]
I think that you should follow the standard Cloudflare guideline:
- Add this  
 "devDependencies": {
        "@cloudflare/next-on-pages": "^0.5.0",
        "vercel": "^28.18.2"
    }
to use Vercel CLI buld tool
- Config build command on Pages: npx @cloudflare/next-on-pages --experimental-minify
- Set output: .vercel/output/static

**Comment by dario-piotrowicz** [comment]
@danielrhodes could you please check if the issue still persist with the latest version of Next.js and next-on-pages? Since @wuomzfx comment makes it sound like it could be fixed by now (also please follow what @ThuKieuIC2 mentioned 🙂)

If you still face the issue could you share some code that reproduces it?

**Comment by dario-piotrowicz** [comment]
I'm closing this issue due to inactivity and since I imagine that it should be solved

@danielrhodes if you circle back to this and still experience some problems please let me know and we can reopen the issue 👍

**Comment by Crinchy** [comment]
Still getting this error on cloudflare pages, cant fetch data from an api in the getServerSideProps function, if i comment the code out, its working. On vercel is the fetch working.

**Comment by dario-piotrowicz** [comment]
> If you still face the issue could you share some code that reproduces it?

I see, I'm sorry to hear that, could you by any chance share a minimal reproduction of it so that we can investigate? :pray: 

(Also I do suspect that this issue is fixed and that you might experiencing something different (maybe with the same error message?) I'd suggest you to open a new issue if you'd like :slightly_smiling_face:)

**Comment by Crinchy** [comment]
The site deployed on vercel https://fakecrime-bio.vercel.app/crinchy
The site deployed on cloudflare pages https://fakecrime-bio.pages.dev/crinchy

Same repository, same environment variables

**Comment by Crinchy** [comment]
This is the code i am running in the getServerSideProps function
```
  const response = await fetch(`${process.env.API_URL}/users/${portfolio.discord}`, {
    headers: {
      'Authorization': process.env.API_AUTHORIZATION || '',
    },
    cache: 'no-store'
  });
```

I configurated everything like the documentation said for nextjs ssr
https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/

**Comment by Crinchy** [comment]
I could find our, i am getting the 500 error, by using the cache: 'no-store' in the fetch
